<a href="https://colab.research.google.com/github/shredder0812/VXLNhom12/blob/test/endo_ocsort_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!cp /content/drive/MyDrive/ENDOCV/Daday_3.mp4 /content/drive/MyDrive/ENDOCV/testtrain/best.pt /content

In [4]:
!pip install ultralytics
!git clone https://github.com/KeeganFernandesWork/yolo_tracking
%cd yolo_tracking
!pip install -r requirements.txt
!pip install .

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 716.0/716.0 kB 4.6 MB/s eta 0:00:00
Cloning into 'yolo_tracking'...
remote: Enumerating objects: 6488, done.
remote: Total 6488 (delta 0), reused 0 (delta 0), pack-reused 6488
Receiving objects: 100% (6488/6488), 107.31 MiB | 34.65 MiB/s, done.
Resolving deltas: 100% (3720/3720), done.
/content/yolo_tracking
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.0/178.0 kB 1.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 195.4/195.4 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 17.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 8.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 45.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.2/204.2 kB 21.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 6.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Processing /content/yolo_tracking
  Preparing metadata (setup.py) ... done
  Created wheel for boxmot: filename=boxmot-10.0.16-py3-none-any.whl size=161019 sha256=d613045ea3f1795f3f434bacadc0b3784170ff706c2786ddf3c3d940990b1603
  Stored in directory: /tmp/pip-ephem-wheel-cache-f_ui8lkp/wheels/d1/7a/9f/544c1c94c1439cc6e243a1761dc7ff1488a5211f244532263a
Successfully built boxmot


In [5]:
from boxmot import (OCSORT, BoTSORT, BYTETracker, DeepOCSORT, StrongSORT,
                    create_tracker, get_tracker_config)
from pathlib import Path
import cv2
import sys
import numpy as np
import datetime
from ultralytics import YOLO

Video Writer

In [40]:
def create_video_writer(video_cap, output_filename):

    # grab the width, height, and fps of the frames in the video stream.
    frame_width = int(video_cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(video_cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = int(video_cap.get(cv2.CAP_PROP_FPS))

    # initialize the FourCC and a video writer object
    fourcc = cv2.VideoWriter_fourcc(*'XVID')
    writer = cv2.VideoWriter(output_filename, fourcc, fps,
                             (frame_width, frame_height))

    return writer

In [41]:
color = (0, 0, 255)  # BGR
thickness = 2
fontscale = 0.5
#device = "cpu" # cuda:0 , cpu
device = "cuda:0" # cuda:0 , cpu
fp16 = True # True if gpu available
# load the pre-trained YOLOv8n model
model = YOLO("/content/best.pt")
source = "/content/Daday_3.mp4"

Testing DeepOCSORT

In [42]:
tracker = DeepOCSORT(
    model_weights=Path('osnet_x0_25_msmt17.pt'), # which ReID model to use
    device=device,
    fp16=fp16,
)
vid = cv2.VideoCapture(source)
writer = create_video_writer(vid, "DeepOCSORT.mp4")



2024-02-23 04:25:20.669 | SUCCESS  | boxmot.appearance.reid_model_factory:load_pretrained_weights:187 - Successfully loaded pretrained weights from "osnet_x0_25_msmt17.pt"
2024-02-23 04:25:20.671 | WARNING  | boxmot.appearance.reid_model_factory:load_pretrained_weights:191 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')


In [59]:
# while True:
#     ret, im = vid.read()

#     detections = model.predict(im )[0]

#     # initialize the list of bounding boxes and confidences
#     results = []
#     if not ret:
#         break
#     boxes_data = np.array(detections.boxes.data.tolist())
#     if boxes_data.ndim < 2:
#         boxes_data = np.array([[0, 0, 0, 0, 0.0922948837280273,0]])
#     else:
#       boxes_data = np.array(detections.boxes.data.tolist())
#     print(boxes_data, '===', boxes_data.shape, '===', len(boxes_data.shape))





0: 512x640 1 polyp, 74.2ms
Speed: 3.9ms preprocess, 74.2ms inference, 2.4ms postprocess per image at shape (1, 3, 512, 640)
[[     632.51      327.38       773.2      474.36     0.41538           0]] === (1, 6) === 2

0: 512x640 1 polyp, 74.2ms
Speed: 6.8ms preprocess, 74.2ms inference, 1.6ms postprocess per image at shape (1, 3, 512, 640)
[[     632.51      327.41      773.23      474.38     0.41799           0]] === (1, 6) === 2

0: 512x640 (no detections), 61.7ms
Speed: 2.4ms preprocess, 61.7ms inference, 1.1ms postprocess per image at shape (1, 3, 512, 640)
[[          0           0           0           0    0.092295           0]] === (1, 6) === 2

0: 512x640 (no detections), 48.9ms
Speed: 2.3ms preprocess, 48.9ms inference, 0.6ms postprocess per image at shape (1, 3, 512, 640)
[[          0           0           0           0    0.092295           0]] === (1, 6) === 2

0: 512x640 (no detections), 47.4ms
Speed: 2.7ms preprocess, 47.4ms inference, 0.7ms postprocess per image at sh

KeyboardInterrupt: 

In [1]:
# test

from pathlib import Path

import numpy as np
from numpy.testing import assert_allclose

from boxmot import (OCSORT, BoTSORT, BYTETracker, DeepOCSORT, StrongSORT,
                    create_tracker, get_tracker_config)
from boxmot.utils import WEIGHTS


def test_deepocsort_output():
    tracker_conf = get_tracker_config('deepocsort')
    tracker = create_tracker(
        tracker_type='deepocsort',
        tracker_config=tracker_conf,
        reid_weights=WEIGHTS / 'mobilenetv2_x1_4_dukemtmcreid.pt',
        device='cpu',
        half=False,
        per_class=False
    )
    rgb = np.random.randint(255, size=(640, 640, 3), dtype=np.uint8)
    det = np.array([[144, 212, 578, 480, 0.82, 0],
                    [425, 281, 576, 472, 0.56, 65]])
    output = tracker.update(det, rgb)
    print(output)
    # Works since frame count is less than min hits (1 <= 2)
    assert output.shape == (2, 7)  # two inputs should give two outputs
    output = np.flip(np.delete(output, 4, axis=1), axis=0)
    assert_allclose(det, output, atol=1, rtol=7e-3, verbose=True)

    # Instantiate new tracker and ensure minimum number of hits works
    tracker = create_tracker(
        tracker_type='deepocsort',
        tracker_config=tracker_conf,
        reid_weights=WEIGHTS / 'mobilenetv2_x1_4_dukemtmcreid.pt',
        device='cpu',
        half=False,
        per_class=False
    )
    tracker.min_hits = 2
    output = tracker.update(np.empty((0, 6)), rgb)
    assert output.size == 0
    output = tracker.update(np.empty((0, 6)), rgb)
    assert output.size == 0
    output = tracker.update(det, rgb)
    assert output.size == 0
    output = tracker.update(det, rgb)
    assert output.size == 0
    output = tracker.update(det, rgb)
    assert output.shape == (2, 7)  # two inputs should give two outputs
    output = tracker.update(det, rgb)
    assert output.shape == (2, 7)  # two inputs should give two outputs
    output = np.flip(np.delete(output, 4, axis=1), axis=0)
    print(output)
    assert_allclose(det, output, atol=1, rtol=7e-3, verbose=True)

test_deepocsort_output()


ModuleNotFoundError: No module named 'boxmot'

In [57]:
while True:
    ret, im = vid.read()

    detections = model.predict(im )[0]

    # initialize the list of bounding boxes and confidences
    results = []
    if not ret:
        break
    boxes_data = np.array(detections.boxes.data.tolist())
    if boxes_data.ndim < 2:
        boxes_data = np.array([[0, 0, 0, 0, 0.0922948837280273,0]])
    else:
      boxes_data = np.array(detections.boxes.data.tolist())
    print(boxes_data, '===', boxes_data.shape, '===', len(boxes_data.shape))


    ts = tracker.update(boxes_data, im) # --> (x, y, x, y, id, conf, cls)
    xyxys = ts[:,0:4].astype('int') # float64 to int
    ids = ts[:, 5].astype('int') # float64 to int
    confs = ts[:, 4]
    clss = ts[:, 5]


    # print bboxes with their associated id, cls and conf
    if ts.shape[0] != 0:
        for xyxy, id, conf, cls in zip(xyxys, ids, confs, clss):
            im = cv2.rectangle(
                im,
                (xyxy[0], xyxy[1]),
                (xyxy[2], xyxy[3]),
                color,
                thickness
            )
            cv2.putText(
                im,
                f'conf: {conf}, c: {cls}',
                (xyxy[0], xyxy[1]-10),
                cv2.FONT_HERSHEY_SIMPLEX,
                fontscale,
                color,
                thickness
            )

    # show the frame to our screen

    writer.write(im)

vid.release()
writer.release()
print("Task Completed")


0: 512x640 1 polyp, 75.9ms
Speed: 2.8ms preprocess, 75.9ms inference, 2.4ms postprocess per image at shape (1, 3, 512, 640)
[[      633.6      327.44      773.62      473.79     0.46983           0]] === (1, 6) === 2


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [37]:
ts = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]])
xyxys = ts[:,0:4].astype('int') # float64 to int
ids = ts[:, 4].astype('int') # float64 to int
confs = ts[:, 5]
clss = ts[:, 0]
print(xyxys)
print(ids)
print(confs)
print(clss)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[5 5 5 5]
[6 6 6 6]
[1 1 1 1]
